### ISSUE TITLE
連結壞了

### ISSUE THREAD

**Issue by yuenu** [nicehorse06/frontend-practice-course#3]
Hi~整理的蠻好的，但我點前面的連結似乎壞了，應該跟你改repo name有關，建議你可以檢查一下

將`software-job-note`改成`se-job`

### 這個專案有什麼資源?
- [網頁前端程式入門筆記](https://github.com/nicehorse06/software-job-note/tree/master/frontend/README.md)，裡面有很多前端學習資源建議
- [前端自學路線建議](https://github.com/nicehorse06/software-job-note/blob/master/frontend/learning_path.md)
持續整理中...

**Comment by mengtsema** [comment]
Hi josh

的確是忘記改連結，已修正
昨天想在PTT分享 但是發現有tag的網址太長了 囧  就改名字
感謝提醒~~~~

Jimmy

josh Hsu ***@***.***> 於 2022年4月29日 週五 上午8:41寫道：
